{...}: {
  imports = [
    ./amfora.nix
    ./cava.nix
    ./binds.nix
    ./emoji.nix
    ./scripts
    ../common/ags
    ../common/bash.nix
    ../common/bashrc-personal.nix
    ../common/btop.nix
    ../common/fastfetch
    ../common/gh.nix
    ../common/ghostty.nix
    ../common/git.nix
    ../common/gtk.nix
    ../common/htop.nix
    ../common/hyprland
    ../common/kitty.nix
    ../common/nixvim.nix
    ../common/rofi
    ../common/qt.nix
    ../common/scripts
    ../common/ssh.nix
    ../common/starship.nix
    ../common/stylix.nix
    ../common/stylix-home.nix
    ../common/swappy.nix
    ../common/virtmanager.nix
    ../common/wezterm.nix
    ../common/wlogout
    ../common/xdg.nix
    ../common/yazi
    ../common/zoxide.nix
    ../common/zsh
  ];
}
